In [1]:
from pathlib import Path
import pandas as pd

DATA_DIR = Path("../data")

rooms = pd.read_json(DATA_DIR / "rooms.json")
students = pd.read_json(DATA_DIR / "students.json")

In [2]:
rooms.head()

   id     name
0   0  Room #0
1   1  Room #1
2   2  Room #2
3   3  Room #3
4   4  Room #4

In [3]:
students.head()

                     birthday  id             name  room sex
0  2011-08-22T00:00:00.000000   0       Peggy Ryan   473   M
1  2004-01-07T00:00:00.000000   1   Christian Bush   743   M
2  2006-12-11T00:00:00.000000   2  Juan Strickland   129   M
3  1915-11-19T00:00:00.000000   3  Nathaniel Clark   355   F
4  2001-08-25T00:00:00.000000   4    Molly Sanchez   227   M

In [4]:
len(rooms), len(students)

(1000, 10000)

In [5]:
rooms["id"].is_unique, students["id"].is_unique

(True, True)

In [6]:
students[students["room"] == 1]

                        birthday    id             name  room sex
541   1990-05-10T00:00:00.000000   541    Eileen Taylor     1   F
976   1993-06-14T00:00:00.000000   976     Amy Williams     1   M
2470  1919-03-08T00:00:00.000000  2470    Angela Gibson     1   M
4044  1950-08-08T00:00:00.000000  4044       Lori Smith     1   F
6410  1989-05-13T00:00:00.000000  6410  Benjamin Ashley     1   M
8634  1913-01-27T00:00:00.000000  8634   Kimberly Young     1   F
8994  2019-09-12T00:00:00.000000  8994    Angela Martin     1   F

In [7]:
students.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   birthday  10000 non-null  str
 1   id        10000 non-null  int64
 2   name      10000 non-null  str
 3   room      10000 non-null  int64
 4   sex       10000 non-null  str
dtypes: int64(2), str(3)
memory usage: 390.8 KB

In [8]:
rooms.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      1000 non-null   int64
 1   name    1000 non-null   str
dtypes: int64(1), str(1)
memory usage: 15.8 KB

In [9]:
students.isna().sum()

birthday    0
id          0
name        0
room        0
sex         0
dtype: int64

In [10]:
students["sex"].value_counts()

sex
F    5014
M    4986
Name: count, dtype: int64

In [11]:
students["room"].isin(rooms["id"]).all()

np.True_

Every student is assigned to an existing room - students["room"] will be a FOREIGN KEY.

In [12]:
(~rooms["id"].isin(students["room"])).sum()

np.int64(1)

one room is empty

In [13]:
rooms[~rooms["id"].isin(students["room"])]

      id       name
482  482  Room #482

In [14]:
students["room"].describe()

count    10000.000000
mean       497.435300
std        288.113594
min          0.000000
25%        249.000000
50%        499.000000
75%        747.000000
max        999.000000
Name: room, dtype: float64

In [15]:
students["room"].value_counts().describe()

count    999.000000
mean      10.010010
std        3.098565
min        2.000000
25%        8.000000
50%       10.000000
75%       12.000000
max       20.000000
Name: count, dtype: float64

In [16]:
rooms["name"].str.len().max()

np.int64(9)

In [17]:
students["name"].str.len().max()

np.int64(27)

PK - id from rooms

FK - room from students

relation many to one (many students to one room)

In [18]:
rooms[["id", "name"]].to_csv(DATA_DIR / "rooms.csv", index=False)
students[["id", "name", "birthday", "sex", "room"]].to_csv(DATA_DIR / "students.csv", index=False)