## The dataset is compiled from the 1994 Census database and contains income data.
### Data Information:
* age: continuous.
* workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
* fnlwgt: continuous.
* education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, * Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
* education-num: continuous.
* marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
* occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
* relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
* race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
* sex: Female, Male.
* capital-gain: continuous.
* capital-loss: continuous.
* hours-per-week: continuous.
* native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
* salary: >50K,<=50K

## Perform data analysis using Pandas by completing the given tasks.
####

In [1]:
import pandas as pd

In [2]:
# loading the dataset
data = pd.read_csv("./data/adult.data.csv")
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. Calculate how many men and women (attribute *sex*) are represented in this dataset.**

In [18]:
data["sex"].value_counts()

sex
Male      21790
Female    10771
Name: count, dtype: int64

**2. What is the average age of men (attribute *age*) across the entire dataset?**

In [23]:
data.loc[data["sex"] == "Male", "age"].mean()

np.float64(39.43354749885268)

**3. What is the proportion of United States citizens (*native-country* attribute)?**

In [30]:
data["native-country"].value_counts(normalize=True)["United-States"]

np.float64(0.895857006848684)

**4-5. Calculate the mean and standard deviation of the age of those who earn more than 50K per year (the *salary* attribute) and those who earn less than 50K per year**

In [32]:
data.groupby("salary")["age"].agg(["mean", "std"])

             mean        std
salary
<=50K   36.783738  14.020088
>50K    44.249841  10.519028

**6. Is it true that people who earn more than 50k have at least a higher education? (*education indicator – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters or Doctorate*)**

In [38]:
higher_edu = [
    "Bachelors",
    "Prof-school",
    "Assoc-acdm",
    "Assoc-voc",
    "Masters",
    "Doctorate",
]
data.loc[data["salary"] == ">50K", "education"].isin(higher_edu).all()

np.False_

**7. Find age statistics for each race (*race* attribute) and each gender. Use *groupby* and *describe*. Find the maximum age of males of the *Asian-Pac-Islander* race.**

In [45]:
stat = data.groupby(["race", "sex"])["age"].describe()
stat.loc[("Asian-Pac-Islander", "Male"), "max"]

np.float64(90.0)

**8. Among whom is the proportion of high-earning individuals (>50K) higher: married or single men (*marital-status* indicator)? We consider those whose *marital-status* begins with *Married* (Married-civ-spouse, Married-spouse-absent, or Married-AF-spouse) to be married; the rest are considered single.**

In [54]:
married = data[
    (data["sex"] == "Male") & (data["marital-status"].str.startswith("Married"))
]
single = data[
    (data["sex"] == "Male") & ~(data["marital-status"].str.startswith("Married"))
]
(married["salary"] == ">50K").mean(), (single["salary"] == ">50K").mean()

(np.float64(0.4405139945351156), np.float64(0.08449509031397745))

**9. What is the maximum number of hours a person works per week (hours-per-week indicator)? How many people work that many hours, and what percentage of them earn a lot?**

In [64]:
max_h = data["hours-per-week"].max()
hard_workers = data[data["hours-per-week"] == max_h]
max_h, len(hard_workers), (hard_workers["salary"] == ">50K").mean()

(np.int64(99), 85, np.float64(0.29411764705882354))

**10. Calculate the average working hours (*hours-per-week*) of low and high earners (*salary*) for each country (*native-country*).**

In [66]:
data.groupby(["native-country", "salary"])["hours-per-week"].mean().unstack()

salary                          <=50K       >50K
native-country
?                           40.164760  45.547945
Cambodia                    41.416667  40.000000
Canada                      37.914634  45.641026
China                       37.381818  38.900000
Columbia                    38.684211  50.000000
Cuba                        37.985714  42.440000
Dominican-Republic          42.338235  47.000000
Ecuador                     38.041667  48.750000
El-Salvador                 36.030928  45.000000
England                     40.483333  44.533333
France                      41.058824  50.750000
Germany                     39.139785  44.977273
Greece                      41.809524  50.625000
Guatemala                   39.360656  36.666667
Haiti                       36.325000  42.750000
Holand-Netherlands          40.000000        NaN
Honduras                    34.333333  60.000000
Hong                        39.142857  45.000000
Hungary                     31.300000  50.000000
India                       38.233333  46.475000
Iran                        41.440000  47.500000
Ireland                     40.947368  48.000000
Italy                       39.625000  45.400000
Jamaica                     38.239437  41.100000
Japan                       41.000000  47.958333
Laos                        40.375000  40.000000
Mexico                      40.003279  46.575758
Nicaragua                   36.093750  37.500000
Outlying-US(Guam-USVI-etc)  41.857143        NaN
Peru                        35.068966  40.000000
Philippines                 38.065693  43.032787
Poland                      38.166667  39.000000
Portugal                    41.939394  41.500000
Puerto-Rico                 38.470588  39.416667
Scotland                    39.444444  46.666667
South                       40.156250  51.437500
Taiwan                      33.774194  46.800000
Thailand                    42.866667  58.333333
Trinadad&Tobago             37.058824  40.000000
United-States               38.799127  45.505369
Vietnam                     37.193548  39.200000
Yugoslavia                  41.600000  49.500000

**11.Group people into age groups *young*, *adult*, *retiree*, where:**
* *young* corresponds to 16-35 years old
* *adult* - 35-70 years old
* *retiree* - 70-100 years old

**Enter the name of the appropriate age group for each person in the new AgeGroup column.**

In [72]:
data["AgeGroup"] = pd.cut(
    data["age"], bins=[16, 35, 70, 100], labels=["young", "adult", "retiree"]
)
data[["age", "AgeGroups"]]

       age AgeGroups
0       39     adult
1       50     adult
2       38     adult
3       53    retire
4       28     adult
...    ...       ...
32556   27     adult
32557   40     adult
32558   58    retire
32559   22     young
32560   52    retire

[32561 rows x 2 columns]

**12-13. Determine the number of people earning >50K in each age group (AgeGroup column), and also output the name of the age group in which people most often earn more than 50K (>50K)**

In [76]:
counts = data.loc[data["salary"] == ">50K", "AgeGroups"].value_counts()
counts, counts.idxmax()

(AgeGroups
 adult     5629
 retire    2098
 young      114
 Name: count, dtype: int64,
 'adult')

**14. Group people by employment type (the occupation column) and determine the number of people in each group. Then write a filter function, filter_func, that will return only those groups in which the average age (the age column) is 40 or less and in which all employees work more than 5 hours per week (the hours-per-week column).**

In [87]:
print(data.groupby("occupation").size())


def filter_func(group):
    return group["age"].mean() <= 40 and (group["hours-per-week"] > 5).all()


data.groupby("occupation").filter(filter_func)

occupation
?                    1843
Adm-clerical         3770
Armed-Forces            9
Craft-repair         4099
Exec-managerial      4066
Farming-fishing       994
Handlers-cleaners    1370
Machine-op-inspct    2002
Other-service        3295
Priv-house-serv       149
Prof-specialty       4140
Protective-serv       649
Sales                3650
Tech-support          928
Transport-moving     1597
dtype: int64

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary,AgeGroups,AgeGroup
442,24,Federal-gov,191073,HS-grad,9,Never-married,Armed-Forces,Own-child,White,Male,0,0,40,United-States,<=50K,young,young
1300,29,Federal-gov,301010,Some-college,10,Never-married,Armed-Forces,Not-in-family,Black,Male,0,0,60,United-States,<=50K,adult,young
14613,39,Federal-gov,227597,HS-grad,9,Never-married,Armed-Forces,Not-in-family,White,Male,0,0,50,United-States,<=50K,adult,adult
16111,24,Federal-gov,287988,Bachelors,13,Never-married,Armed-Forces,Not-in-family,White,Male,0,0,40,United-States,<=50K,young,young
18034,34,Federal-gov,172716,12th,8,Married-civ-spouse,Armed-Forces,Husband,White,Male,0,0,40,United-States,<=50K,adult,young
18644,23,Federal-gov,163870,Some-college,10,Never-married,Armed-Forces,Other-relative,White,Male,0,0,40,United-States,<=50K,young,young
18769,30,Federal-gov,76313,HS-grad,9,Married-civ-spouse,Armed-Forces,Other-relative,Amer-Indian-Eskimo,Male,0,0,48,United-States,<=50K,adult,young
25799,46,Federal-gov,344415,Masters,14,Married-civ-spouse,Armed-Forces,Husband,White,Male,0,1887,40,United-States,>50K,adult,adult
32316,23,Federal-gov,173851,HS-grad,9,Never-married,Armed-Forces,Not-in-family,White,Male,0,0,8,United-States,<=50K,young,young